package main

import (
	"flag"
	"fmt"
	"os"
	"runtime/debug"
	"time"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

// version can be set at build time via ldflags
var version string

func init() {
	// If version was set via ldflags, use it
	if version != "" {
		return
	}

	// Try to get version from Go module info (works with go install)
	if info, ok := debug.ReadBuildInfo(); ok && info.Main.Version != "" {
		version = info.Main.Version
		return
	}

	version = "development"
}

func main() {
	var flags flag.FlagSet

	// Get the flags
	showVersion := flag.Bool("version", false, "Print the version of protoc-gen-go-jsonschema")
	flag.Parse()

	if *showVersion {
		fmt.Printf("%s\n", version)
		os.Exit(0)
	}

	options := protogen.Options{
		ParamFunc: flags.Set,
	}

	options.Run(func(p *protogen.Plugin) error {
		p.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		return Generate(p, version)
	})
}

func Generate(plugin *protogen.Plugin, version string) error {
	for _, f := range plugin.Files {
		if !f.Generate {
			continue
		}

		if _, err := generateFile(plugin, f); err != nil {
			plugin.Error(err)
			return err
		}
	}

	return nil
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) (*protogen.GeneratedFile, error) {
	filename := file.GeneratedFilenamePrefix + ".pb.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	// Write file header with generation metadata.
	// This helps identify generated files and track their source.
	{
		g.P("// Package ", file.GoPackageName, " was generated from ", file.Desc.Path())
		g.P("// Code generated by https://github.com/DanielvNiek/protoc-gen-easyproto. DO NOT EDIT.")
		g.P("// ")
		g.P("// Source: ", file.Desc.Path())
		g.P("// Plugin version: ", version)
		g.P("// ")
		g.P("// Generated on: ", time.Now().UTC().Format("2006-01-02 15:04:05"), " UTC")
		g.P("package ", file.GoPackageName)
	}
	return g, nil
}
