// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pb/test.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A test enum.
type TestEnum int32

const (
	// TEST_ENUM_UNSPECIFIED is the default value.
	TestEnum_TEST_ENUM_UNSPECIFIED TestEnum = 0
	// TEST_ENUM_VALUE_1 is the first value.
	TestEnum_TEST_ENUM_VALUE_1 TestEnum = 1
	// TEST_ENUM_VALUE_2 is the second value.
	TestEnum_TEST_ENUM_VALUE_2 TestEnum = 2
)

// Enum value maps for TestEnum.
var (
	TestEnum_name = map[int32]string{
		0: "TEST_ENUM_UNSPECIFIED",
		1: "TEST_ENUM_VALUE_1",
		2: "TEST_ENUM_VALUE_2",
	}
	TestEnum_value = map[string]int32{
		"TEST_ENUM_UNSPECIFIED": 0,
		"TEST_ENUM_VALUE_1":     1,
		"TEST_ENUM_VALUE_2":     2,
	}
)

func (x TestEnum) Enum() *TestEnum {
	p := new(TestEnum)
	*p = x
	return p
}

func (x TestEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_test_proto_enumTypes[0].Descriptor()
}

func (TestEnum) Type() protoreflect.EnumType {
	return &file_pb_test_proto_enumTypes[0]
}

func (x TestEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestEnum.Descriptor instead.
func (TestEnum) EnumDescriptor() ([]byte, []int) {
	return file_pb_test_proto_rawDescGZIP(), []int{0}
}

// A test message.
type Test struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The test name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The test age.
	// Between 0 and 100, inclusive.
	Age int32 `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	// NICKNAMES
	Nicknames []string `protobuf:"bytes,3,rep,name=nicknames,proto3" json:"nicknames,omitempty"`
	// The test status.
	Status TestEnum `protobuf:"varint,4,opt,name=status,proto3,enum=pb.TestEnum" json:"status,omitempty"`
	// The test statuses.
	Statuses      []TestEnum         `protobuf:"varint,5,rep,packed,name=statuses,proto3,enum=pb.TestEnum" json:"statuses,omitempty"`
	Tags          map[string]string  `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnumMap       map[int32]TestEnum `protobuf:"bytes,7,rep,name=enum_map,json=enumMap,proto3" json:"enum_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=pb.TestEnum"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test) Reset() {
	*x = Test{}
	mi := &file_pb_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_pb_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_pb_test_proto_rawDescGZIP(), []int{0}
}

func (x *Test) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Test) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Test) GetNicknames() []string {
	if x != nil {
		return x.Nicknames
	}
	return nil
}

func (x *Test) GetStatus() TestEnum {
	if x != nil {
		return x.Status
	}
	return TestEnum_TEST_ENUM_UNSPECIFIED
}

func (x *Test) GetStatuses() []TestEnum {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *Test) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Test) GetEnumMap() map[int32]TestEnum {
	if x != nil {
		return x.EnumMap
	}
	return nil
}

var File_pb_test_proto protoreflect.FileDescriptor

const file_pb_test_proto_rawDesc = "" +
	"\n" +
	"\rpb/test.proto\x12\x02pb\"\xf7\x02\n" +
	"\x04Test\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x1c\n" +
	"\tnicknames\x18\x03 \x03(\tR\tnicknames\x12$\n" +
	"\x06status\x18\x04 \x01(\x0e2\f.pb.TestEnumR\x06status\x12(\n" +
	"\bstatuses\x18\x05 \x03(\x0e2\f.pb.TestEnumR\bstatuses\x12&\n" +
	"\x04tags\x18\x06 \x03(\v2\x12.pb.Test.TagsEntryR\x04tags\x120\n" +
	"\benum_map\x18\a \x03(\v2\x15.pb.Test.EnumMapEntryR\aenumMap\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aH\n" +
	"\fEnumMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\x0e2\f.pb.TestEnumR\x05value:\x028\x01*S\n" +
	"\bTestEnum\x12\x19\n" +
	"\x15TEST_ENUM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TEST_ENUM_VALUE_1\x10\x01\x12\x15\n" +
	"\x11TEST_ENUM_VALUE_2\x10\x02B\x0eZ\feasyproto/pbb\x06proto3"

var (
	file_pb_test_proto_rawDescOnce sync.Once
	file_pb_test_proto_rawDescData []byte
)

func file_pb_test_proto_rawDescGZIP() []byte {
	file_pb_test_proto_rawDescOnce.Do(func() {
		file_pb_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_test_proto_rawDesc), len(file_pb_test_proto_rawDesc)))
	})
	return file_pb_test_proto_rawDescData
}

var file_pb_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_test_proto_goTypes = []any{
	(TestEnum)(0), // 0: pb.TestEnum
	(*Test)(nil),  // 1: pb.Test
	nil,           // 2: pb.Test.TagsEntry
	nil,           // 3: pb.Test.EnumMapEntry
}
var file_pb_test_proto_depIdxs = []int32{
	0, // 0: pb.Test.status:type_name -> pb.TestEnum
	0, // 1: pb.Test.statuses:type_name -> pb.TestEnum
	2, // 2: pb.Test.tags:type_name -> pb.Test.TagsEntry
	3, // 3: pb.Test.enum_map:type_name -> pb.Test.EnumMapEntry
	0, // 4: pb.Test.EnumMapEntry.value:type_name -> pb.TestEnum
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pb_test_proto_init() }
func file_pb_test_proto_init() {
	if File_pb_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_test_proto_rawDesc), len(file_pb_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_test_proto_goTypes,
		DependencyIndexes: file_pb_test_proto_depIdxs,
		EnumInfos:         file_pb_test_proto_enumTypes,
		MessageInfos:      file_pb_test_proto_msgTypes,
	}.Build()
	File_pb_test_proto = out.File
	file_pb_test_proto_goTypes = nil
	file_pb_test_proto_depIdxs = nil
}
